apiVersion: v1
kind: Namespace
metadata:
  name: lab-test-uac
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-uac
  namespace: lab-test-uac
  labels:
    app: backend-nest-test-uac
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-uac
  template:
    metadata:
      labels:
        app: backend-nest-test-uac
    spec:
      containers:
      - name: backend-nest-test-uac
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-uac
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
--- 
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-test-uac-svc
  namespace: lab-test-uac
  labels:
    app: backend-nest-test-uac-svc
spec:
  selector:
     app: backend-nest-test-uac
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4006
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-test-uac
  namespace: lab-test-uac
spec:
  ingressClassName: nginx
  rules:
  - host: uac.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-nest-test-uac-svc
            port:
              number: 80